
/**************************** Script Header ******************************/
SET @File_script_name := 'DCR_010_005007_OGPLUS_t_dealers_UPDATE.sql';
SET @Author_Name := 'Alfie Salano';
SET @Database_Version := '1.0';
SET @Change_request_cd := 'C-005007';
SET @Script_Description :='Add new Dealers Name';
SET @Rollback_Script_name := 'ROLLBACK_DCR_010_005007_OGPLUS_t_dealers_REMOVE.sql';

/********************** Constants No change here **************************/

SELECT DATABASE() INTO @database_name;

CALL `utility`.`sp_script_log_insert`(
	@File_script_name,
	@Author_Name,
	@Database_Version,
	@database_name,
	@Change_request_cd,
	@Script_Description,
	@Rollback_Script_name,
	@script_log_id
);

/**************************** Main Script Here ******************************/

REPLACE INTO `t_dealers` (`id`, `dealerscode`, `fullname`, `nickname`, `height`, `vitalstats`, `hobbies`, `birthday`, `followers`, `imageclassic`, `imagegrand`, `imageprestige`, `imagemanbetx`, `imagestreamer`, `languages`, `tableLocation`) VALUES	
	(222, 956, 'ABIERTAS,  CELESTE', 'YSHII', '5\'0', '0 A, 0 0', '', '1900-01-01', 0, 'https://static.oriental-game.com/dealers/classic/yshii.png', 'https://static.oriental-game.com/dealers/grand/yshii.png', 'https://static.oriental-game.com/dealers/prestige/yshii.png', 'https://static.hzgelf.com/dealers/manbetx/yshii.png', 'https://static.oriental-game.com/dealers/emcee/yshii.jpg', 'en', 'Lobby'),
	(303, 115, 'OBENARIO,  JOSHUA JOY', 'GABI', '5\'0', '0 A, 0 0', '', '1900-01-01', 0, 'https://static.oriental-game.com/dealers/classic/gabi.png', 'https://static.oriental-game.com/dealers/grand/gabi.png', 'https://static.oriental-game.com/dealers/prestige/gabi.png', 'https://static.hzgelf.com/dealers/manbetx/gabi.png', 'https://static.oriental-game.com/dealers/emcee/gabi.jpg', 'en', 'Lobby'),
	(304, 120, 'VIADO,  LOVELY', 'VI', '5\'0', '0 A, 0 0', '', '1900-01-01', 0, 'https://static.oriental-game.com/dealers/classic/vi.png', 'https://static.oriental-game.com/dealers/grand/vi.png', 'https://static.oriental-game.com/dealers/prestige/vi.png', 'https://static.hzgelf.com/dealers/manbetx/vi.png', 'https://static.oriental-game.com/dealers/emcee/vi.jpg', 'en', 'Lobby'),
	(305, 127, 'CAWAS,  JESSICA', 'JES', '5\'0', '0 A, 0 0', '', '1900-01-01', 0, 'https://static.oriental-game.com/dealers/classic/jes.png', 'https://static.oriental-game.com/dealers/grand/jes.png', 'https://static.oriental-game.com/dealers/prestige/jes.png', 'https://static.hzgelf.com/dealers/manbetx/jes.png', 'https://static.oriental-game.com/dealers/emcee/jes.jpg', 'en', 'Lobby'),
	(306, 149, 'IBARROLA,  DIA', 'DIA', '5\'0', '0 A, 0 0', '', '1900-01-01', 0, 'https://static.oriental-game.com/dealers/classic/dia.png', 'https://static.oriental-game.com/dealers/grand/dia.png', 'https://static.oriental-game.com/dealers/prestige/dia.png', 'https://static.hzgelf.com/dealers/manbetx/dia.png', 'https://static.oriental-game.com/dealers/emcee/dia.jpg', 'en', 'Lobby'),
	(307, 151, 'MARCOS,  ANN MARJORIE', 'ANN', '5\'0', '0 A, 0 0', '', '1900-01-01', 0, 'https://static.oriental-game.com/dealers/classic/ann.png', 'https://static.oriental-game.com/dealers/grand/ann.png', 'https://static.oriental-game.com/dealers/prestige/ann.png', 'https://static.hzgelf.com/dealers/manbetx/ann.png', 'https://static.oriental-game.com/dealers/emcee/ann.jpg', 'en', 'Lobby'),
	(308, 157, 'SOLANO,  LOVELY MARIE', 'LOVE', '5\'0', '0 A, 0 0', '', '1900-01-01', 0, 'https://static.oriental-game.com/dealers/classic/love.png', 'https://static.oriental-game.com/dealers/grand/love.png', 'https://static.oriental-game.com/dealers/prestige/love.png', 'https://static.hzgelf.com/dealers/manbetx/love.png', 'https://static.oriental-game.com/dealers/emcee/love.jpg', 'en', 'Lobby'),
	(309, 161, 'GARCIA,  PATRICIA', 'PAT', '5\'0', '0 A, 0 0', '', '1900-01-01', 0, 'https://static.oriental-game.com/dealers/classic/pat.png', 'https://static.oriental-game.com/dealers/grand/pat.png', 'https://static.oriental-game.com/dealers/prestige/pat.png', 'https://static.hzgelf.com/dealers/manbetx/pat.png', 'https://static.oriental-game.com/dealers/emcee/pat.jpg', 'en', 'Lobby'),
	(310, 179, 'DE LEON,  CRISTINA ANGELICA', 'CRIS', '5\'0', '0 A, 0 0', '', '1900-01-01', 0, 'https://static.oriental-game.com/dealers/classic/cris.png', 'https://static.oriental-game.com/dealers/grand/cris.png', 'https://static.oriental-game.com/dealers/prestige/cris.png', 'https://static.hzgelf.com/dealers/manbetx/cris.png', 'https://static.oriental-game.com/dealers/emcee/cris.jpg', 'en', 'Lobby'),
	(311, 182, 'SANTIANO,  PAMELA', 'PATRICE', '5\'0', '0 A, 0 0', '', '1900-01-01', 0, 'https://static.oriental-game.com/dealers/classic/patrice.png', 'https://static.oriental-game.com/dealers/grand/patrice.png', 'https://static.oriental-game.com/dealers/prestige/patrice.png', 'https://static.hzgelf.com/dealers/manbetx/patrice.png', 'https://static.oriental-game.com/dealers/emcee/patrice.jpg', 'en', 'Lobby'),
	(312, 186, 'ANDRES,  DARYL THEA', 'JADE', '5\'0', '0 A, 0 0', '', '1900-01-01', 0, 'https://static.oriental-game.com/dealers/classic/jade.png', 'https://static.oriental-game.com/dealers/grand/jade.png', 'https://static.oriental-game.com/dealers/prestige/jade.png', 'https://static.hzgelf.com/dealers/manbetx/jade.png', 'https://static.oriental-game.com/dealers/emcee/jade.jpg', 'en', 'Lobby'),
	(313, 600, 'DELA ROSA,  JANINE GRACE', 'MAXIME', '5\'0', '0 A, 0 0', '', '1900-01-01', 0, 'https://static.oriental-game.com/dealers/classic/maxime.png', 'https://static.oriental-game.com/dealers/grand/maxime.png', 'https://static.oriental-game.com/dealers/prestige/maxime.png', 'https://static.hzgelf.com/dealers/manbetx/maxime.png', 'https://static.oriental-game.com/dealers/emcee/maxime.jpg', 'en', 'Lobby'),
	(314, 612, 'DIEL,  JESSA MAE', 'DRIA', '5\'0', '0 A, 0 0', '', '1900-01-01', 0, 'https://static.oriental-game.com/dealers/classic/dria.png', 'https://static.oriental-game.com/dealers/grand/dria.png', 'https://static.oriental-game.com/dealers/prestige/dria.png', 'https://static.hzgelf.com/dealers/manbetx/dria.png', 'https://static.oriental-game.com/dealers/emcee/dria.jpg', 'en', 'Lobby'),
	(315, 738, 'VALENCIA,  JULINA', 'ANGELE', '5\'0', '0 A, 0 0', '', '1900-01-01', 0, 'https://static.oriental-game.com/dealers/classic/angele.png', 'https://static.oriental-game.com/dealers/grand/angele.png', 'https://static.oriental-game.com/dealers/prestige/angele.png', 'https://static.hzgelf.com/dealers/manbetx/angele.png', 'https://static.oriental-game.com/dealers/emcee/angele.jpg', 'en', 'Lobby'),
	(316, 751, 'DIOCAMPO,  GRACE', 'GRACE', '5\'0', '0 A, 0 0', '', '1900-01-01', 0, 'https://static.oriental-game.com/dealers/classic/grace.png', 'https://static.oriental-game.com/dealers/grand/grace.png', 'https://static.oriental-game.com/dealers/prestige/grace.png', 'https://static.hzgelf.com/dealers/manbetx/grace.png', 'https://static.oriental-game.com/dealers/emcee/grace.jpg', 'en', 'Lobby'),
	(317, 763, 'DEOCADEZ,  KIRSTY KAELA', 'KAELA', '5\'0', '0 A, 0 0', '', '1900-01-01', 0, 'https://static.oriental-game.com/dealers/classic/kaela.png', 'https://static.oriental-game.com/dealers/grand/kaela.png', 'https://static.oriental-game.com/dealers/prestige/kaela.png', 'https://static.hzgelf.com/dealers/manbetx/kaela.png', 'https://static.oriental-game.com/dealers/emcee/kaela.jpg', 'en', 'Lobby'),
	(318, 764, 'ALHAMBRA,  JAMAICA', 'AICS', '5\'0', '0 A, 0 0', '', '1900-01-01', 0, 'https://static.oriental-game.com/dealers/classic/aics.png', 'https://static.oriental-game.com/dealers/grand/aics.png', 'https://static.oriental-game.com/dealers/prestige/aics.png', 'https://static.hzgelf.com/dealers/manbetx/aics.png', 'https://static.oriental-game.com/dealers/emcee/aics.jpg', 'en', 'Lobby'),
	(319, 821, 'NOJARA,  ANGELICA', 'JING', '5\'0', '0 A, 0 0', '', '1900-01-01', 0, 'https://static.oriental-game.com/dealers/classic/jing.png', 'https://static.oriental-game.com/dealers/grand/jing.png', 'https://static.oriental-game.com/dealers/prestige/jing.png', 'https://static.hzgelf.com/dealers/manbetx/jing.png', 'https://static.oriental-game.com/dealers/emcee/jing.jpg', 'en', 'Lobby'),
	(320, 850, 'MOLINA,  CHARMAINE', 'SKYE', '5\'0', '0 A, 0 0', '', '1900-01-01', 0, 'https://static.oriental-game.com/dealers/classic/skye.png', 'https://static.oriental-game.com/dealers/grand/skye.png', 'https://static.oriental-game.com/dealers/prestige/skye.png', 'https://static.hzgelf.com/dealers/manbetx/skye.png', 'https://static.oriental-game.com/dealers/emcee/skye.jpg', 'en', 'Lobby'),
	(321, 874, 'DE LEON,  ARA MINA', 'VANYA', '5\'0', '0 A, 0 0', '', '1900-01-01', 0, 'https://static.oriental-game.com/dealers/classic/vanya.png', 'https://static.oriental-game.com/dealers/grand/vanya.png', 'https://static.oriental-game.com/dealers/prestige/vanya.png', 'https://static.hzgelf.com/dealers/manbetx/vanya.png', 'https://static.oriental-game.com/dealers/emcee/vanya.jpg', 'en', 'Lobby'),
	(322, 957, 'AGUAS,  JENNIFER', 'SUMI', '5\'0', '0 A, 0 0', '', '1900-01-01', 0, 'https://static.oriental-game.com/dealers/classic/sumi.png', 'https://static.oriental-game.com/dealers/grand/sumi.png', 'https://static.oriental-game.com/dealers/prestige/sumi.png', 'https://static.hzgelf.com/dealers/manbetx/sumi.png', 'https://static.oriental-game.com/dealers/emcee/sumi.jpg', 'en', 'Lobby'),
	(323, 958, 'ARVELO,  ARIANNA', 'SEIKA', '5\'0', '0 A, 0 0', '', '1900-01-01', 0, 'https://static.oriental-game.com/dealers/classic/seika.png', 'https://static.oriental-game.com/dealers/grand/seika.png', 'https://static.oriental-game.com/dealers/prestige/seika.png', 'https://static.hzgelf.com/dealers/manbetx/seika.png', 'https://static.oriental-game.com/dealers/emcee/seika.jpg', 'en', 'Lobby'),
	(324, 959, 'CABILANGAN,  WENCY', 'KNIGHT', '5\'0', '0 A, 0 0', '', '1900-01-01', 0, 'https://static.oriental-game.com/dealers/classic/knight.png', 'https://static.oriental-game.com/dealers/grand/knight.png', 'https://static.oriental-game.com/dealers/prestige/knight.png', 'https://static.hzgelf.com/dealers/manbetx/knight.png', 'https://static.oriental-game.com/dealers/emcee/knight.jpg', 'en', 'Lobby'),
	(325, 960, 'GALANG,  JANELLA', 'YOONA', '5\'0', '0 A, 0 0', '', '1900-01-01', 0, 'https://static.oriental-game.com/dealers/classic/yoona.png', 'https://static.oriental-game.com/dealers/grand/yoona.png', 'https://static.oriental-game.com/dealers/prestige/yoona.png', 'https://static.hzgelf.com/dealers/manbetx/yoona.png', 'https://static.oriental-game.com/dealers/emcee/yoona.jpg', 'en', 'Lobby'),
	(326, 961, 'MAGLASANG,  NINA', 'CHLOE', '5\'0', '0 A, 0 0', '', '1900-01-01', 0, 'https://static.oriental-game.com/dealers/classic/chloe.png', 'https://static.oriental-game.com/dealers/grand/chloe.png', 'https://static.oriental-game.com/dealers/prestige/chloe.png', 'https://static.hzgelf.com/dealers/manbetx/chloe.png', 'https://static.oriental-game.com/dealers/emcee/chloe.jpg', 'en', 'Lobby'),
	(327, 962, 'MERCULIO,  ROVELYN', 'IRIS', '5\'0', '0 A, 0 0', '', '1900-01-01', 0, 'https://static.oriental-game.com/dealers/classic/iris.png', 'https://static.oriental-game.com/dealers/grand/iris.png', 'https://static.oriental-game.com/dealers/prestige/iris.png', 'https://static.hzgelf.com/dealers/manbetx/iris.png', 'https://static.oriental-game.com/dealers/emcee/iris.jpg', 'en', 'Lobby'),
	(328, 963, 'NEBRES,  ARJANE', 'DANNA', '5\'0', '0 A, 0 0', '', '1900-01-01', 0, 'https://static.oriental-game.com/dealers/classic/danna.png', 'https://static.oriental-game.com/dealers/grand/danna.png', 'https://static.oriental-game.com/dealers/prestige/danna.png', 'https://static.hzgelf.com/dealers/manbetx/danna.png', 'https://static.oriental-game.com/dealers/emcee/danna.jpg', 'en', 'Lobby'),
	(329, 964, 'TAMAYO,  ELLAINE JOY', 'NICOLE', '5\'0', '0 A, 0 0', '', '1900-01-01', 0, 'https://static.oriental-game.com/dealers/classic/nicole.png', 'https://static.oriental-game.com/dealers/grand/nicole.png', 'https://static.oriental-game.com/dealers/prestige/nicole.png', 'https://static.hzgelf.com/dealers/manbetx/nicole.png', 'https://static.oriental-game.com/dealers/emcee/nicole.jpg', 'en', 'Lobby'),
	(330, 965, 'CAMAGANCAN,  TEDGIE', 'LOUISE', '5\'0', '0 A, 0 0', '', '1900-01-01', 0, 'https://static.oriental-game.com/dealers/classic/louise.png', 'https://static.oriental-game.com/dealers/grand/louise.png', 'https://static.oriental-game.com/dealers/prestige/louise.png', 'https://static.hzgelf.com/dealers/manbetx/louise.png', 'https://static.oriental-game.com/dealers/emcee/louise.jpg', 'en', 'Lobby'),
	(331, 966, 'MAETINEZ,  ALIANA', 'JENNER', '5\'0', '0 A, 0 0', '', '1900-01-01', 0, 'https://static.oriental-game.com/dealers/classic/jenner.png', 'https://static.oriental-game.com/dealers/grand/jenner.png', 'https://static.oriental-game.com/dealers/prestige/jenner.png', 'https://static.hzgelf.com/dealers/manbetx/jenner.png', 'https://static.oriental-game.com/dealers/emcee/jenner.jpg', 'en', 'Lobby'),
	(332, 967, 'CHOU,  YI HSUAN', 'MIKA', '5\'0', '0 A, 0 0', '', '1900-01-01', 0, 'https://static.oriental-game.com/dealers/classic/mika.png', 'https://static.oriental-game.com/dealers/grand/mika.png', 'https://static.oriental-game.com/dealers/prestige/mika.png', 'https://static.hzgelf.com/dealers/manbetx/mika.png', 'https://static.oriental-game.com/dealers/emcee/mika.jpg', 'cn', 'Lobby'),
	(333, 968, 'BANDIGAN,  MARIA CELESTE', 'MC', '5\'0', '0 A, 0 0', '', '1900-01-01', 0, 'https://static.oriental-game.com/dealers/classic/mc.png', 'https://static.oriental-game.com/dealers/grand/mc.png', 'https://static.oriental-game.com/dealers/prestige/mc.png', 'https://static.hzgelf.com/dealers/manbetx/mc.png', 'https://static.oriental-game.com/dealers/emcee/mc.jpg', 'jp', 'Lobby'),
	(334, 969, 'JUANGA,  CHRISTINE MARIE', 'HANEUL', '5\'0', '0 A, 0 0', '', '1900-01-01', 0, 'https://static.oriental-game.com/dealers/classic/haneul.png', 'https://static.oriental-game.com/dealers/grand/haneul.png', 'https://static.oriental-game.com/dealers/prestige/haneul.png', 'https://static.hzgelf.com/dealers/manbetx/haneul.png', 'https://static.oriental-game.com/dealers/emcee/haneul.jpg', 'ko', 'Lobby'),
	(335, 970, 'CALALIN,  MELO JANE', 'MELO', '5\'0', '0 A, 0 0', '', '1900-01-01', 0, 'https://static.oriental-game.com/dealers/classic/melo.png', 'https://static.oriental-game.com/dealers/grand/melo.png', 'https://static.oriental-game.com/dealers/prestige/melo.png', 'https://static.hzgelf.com/dealers/manbetx/melo.png', 'https://static.oriental-game.com/dealers/emcee/melo.jpg', 'en', 'Lobby'),
	(336, 971, 'LUMIBAO,  SHAIRA', 'XHIN', '5\'0', '0 A, 0 0', '', '1900-01-01', 0, 'https://static.oriental-game.com/dealers/classic/xhin.png', 'https://static.oriental-game.com/dealers/grand/xhin.png', 'https://static.oriental-game.com/dealers/prestige/xhin.png', 'https://static.hzgelf.com/dealers/manbetx/xhin.png', 'https://static.oriental-game.com/dealers/emcee/xhin.jpg', 'en', 'Lobby');
	
/**************************** Logging Script ******************************/
CALL `utility`.`sp_script_log_update`(@script_log_id);


/**************************** End of Script ******************************/