INSERT INTO t_dealers
  (fullname, nickname, dealerscode, languages, imageclassic, imagegrand, imageprestige, imagemanbetx)
VALUES
  ("AGAPAY, HENLYN","arkie",849,"en","https://og-333.s3.amazonaws.com/assets/dealers/classic/arkie.png","https://og-333.s3.amazonaws.com/assets/dealers/grand/arkie.png","https://og-333.s3.amazonaws.com/assets/dealers/prestige/arkie.png","https://og-333.s3.amazonaws.com/assets/dealers/manbetx/arkie.png"),
  ("MOLINA, CHARMAINE","skye",850,"en","https://og-333.s3.amazonaws.com/assets/dealers/classic/skye.png","https://og-333.s3.amazonaws.com/assets/dealers/grand/skye.png","https://og-333.s3.amazonaws.com/assets/dealers/prestige/skye.png","https://og-333.s3.amazonaws.com/assets/dealers/manbetx/skye.png"),
  ("MONTEALEGRE, CELENE","macey",851,"en","https://og-333.s3.amazonaws.com/assets/dealers/classic/macey.png","https://og-333.s3.amazonaws.com/assets/dealers/grand/macey.png","https://og-333.s3.amazonaws.com/assets/dealers/prestige/macey.png","https://og-333.s3.amazonaws.com/assets/dealers/manbetx/macey.png"),
  ("GUTIERREZ, ELLAINE","laine",852,"en","https://og-333.s3.amazonaws.com/assets/dealers/classic/laine.png","https://og-333.s3.amazonaws.com/assets/dealers/grand/laine.png","https://og-333.s3.amazonaws.com/assets/dealers/prestige/laine.png","https://og-333.s3.amazonaws.com/assets/dealers/manbetx/laine.png"),
  ("RITO, NISSI", "nice",853,"en","https://og-333.s3.amazonaws.com/assets/dealers/classic/nice.png","https://og-333.s3.amazonaws.com/assets/dealers/grand/nice.png","https://og-333.s3.amazonaws.com/assets/dealers/prestige/nice.png","https://og-333.s3.amazonaws.com/assets/dealers/manbetx/nice.png"),
  ("FRANCISCO, ROSELLE","rosel",854,"en","https://og-333.s3.amazonaws.com/assets/dealers/classic/rosel.png","https://og-333.s3.amazonaws.com/assets/dealers/grand/rosel.png","https://og-333.s3.amazonaws.com/assets/dealers/prestige/rosel.png","https://og-333.s3.amazonaws.com/assets/dealers/manbetx/rosel.png"),
  ("DONGUINES, CAISA","cai",855,"en","https://og-333.s3.amazonaws.com/assets/dealers/classic/cai.png","https://og-333.s3.amazonaws.com/assets/dealers/grand/cai.png","https://og-333.s3.amazonaws.com/assets/dealers/prestige/cai.png","https://og-333.s3.amazonaws.com/assets/dealers/manbetx/cai.png"),
  ("BACALAN, ALMAR", "marla",848,"en","https://og-333.s3.amazonaws.com/assets/dealers/classic/marla.png","https://og-333.s3.amazonaws.com/assets/dealers/grand/marla.png","https://og-333.s3.amazonaws.com/assets/dealers/prestige/marla.png","https://og-333.s3.amazonaws.com/assets/dealers/manbetx/marla.png"),
  ("SUA HUI YENG JEANNA",",eanna",856,"cn","https://og-333.s3.amazonaws.com/assets/dealers/classic/eanna.png","https://og-333.s3.amazonaws.com/assets/dealers/grand/eanna.png","https://og-333.s3.amazonaws.com/assets/dealers/prestige/eanna.png","https://og-333.s3.amazonaws.com/assets/dealers/manbetx/eanna.png");
